### PR TITLE
[6.x] add bridge networking build target (#6)

### PR DESCRIPTION
**Pull request by graphaelli**
Backports the following commits to 6.x:
 - add bridge networking build target  (#6)
 - Be more flexible with Python 3 version. (#11)

### CODE REVIEW

**Comment by dliappis** [comment]
#11 needs to be integrated here to prevent automated builds breaking

**Comment by graphaelli** [comment]
added #11, merging this one first and then will follow with the other backports if all is well.

**Comment by graphaelli** [comment]
@dliappis everything good following this merge?

**Comment by dliappis** [comment]
So far so good @graphaelli thank you for following up!

**Pull request merged**
