### PR TITLE
WIP on env var config

### PR DESCRIPTION
**Pull request by roncohen**

### CODE REVIEW

**Comment by roncohen** [comment]
just doodling. Initial thoughts @jarpy ?

**Comment by DanielTimLee** [comment]
Fantastic.
That's what I was talking about. :+1: 

https://discuss.elastic.co/t/why-apm-server-docker-image-cant-configure-with-environment-variables/114229

I'll catch up if anything comes up in mind.

**Comment by roncohen** [comment]
It seems we should just reuse this if possible: https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/bin/docker-entrypoint.sh#L49-L60

**Comment by roncohen** [comment]
possibly relevant for @elastic/beats as well

**Comment by jarpy** [comment]
My initial thinking here was that it's hard to do anything meaningful in Beats without some site-specific config, and since that config is a complex data structure, trying to represent it with environment variables would be a nightmare. Thus, since Beats users are essentially required to introduce a custom YAML configuration file, then there's not much point supporting the env var config mechanism. However, since there is a demonstrated desire to support at least a subset of configuration options as environment variables, then I don't see why we can't do it.

I do much prefer a generic approach, if at all possible. Using a templated config file causes a couple of problems:

* The file has to be maintained as features are added
* If the user replaces the (carefully crafted) template with their own file, any evn vars they may have been using will stop working

**Comment by roncohen** [comment]
thanks @jarpy 

> I do much prefer a generic approach, if at all possible. Using a templated config file causes a couple of problems:

I agree. You're arguing for reusing this?: https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/bin/docker-entrypoint.sh#L49-L60

**Comment by tsg** [comment]
Beats/apm-server support the `-E` flag, so the same approach as we have for ES should work. +1 to the idea.

**Comment by jarpy** [comment]
> I agree. You're arguing for reusing this?

We could potentially do something like that, but there's a catch. Elasticsearch has the handy property that you can identify its settings by the dots in their names. This means that if you see an environment variable with a dot in it, you can assume it's an Elasticsearch setting. That's what our wrapper does. With Beats (and Logstash, and Kibana), there are some short setting names, with nothing to distinguish them, like `name`. How do we know that the env var `$NAME` or `$name` is a Beats setting, but the env var `$PATH` is not? If we send `-E PATH=/usr/...` to Beats, it will crash.

This is what led to the Kibana and Logstash images having a list of "blessed" settings that are allowed to map from environment variables to command line switches. This is explicit, precise, safe. It's also a maintenance headache, since every new setting has to be double-declared. If we forget to bless a setting (and we've done that), users simpy can't set it with an environment variable.

A grand, unified configuration system for all the images is an unsolved problem, but a future version may involve namespacing (`$METRICBEAT_NAME`). It's tough to make the configuration for all the images the same, since the upstream products themselves have subtle differences in their command line behaviour.

cc @michaelbaamonde

**Comment by roncohen** [comment]
I see. A blessed list is probably the best we can do at the moment. We could potentially extend the config library to generate it from these https://github.com/elastic/apm-server/blob/master/beater/config.go

An alternative would be to take anything that is prefixed with `APM_SERVER_` or `METRICBEAT_`, but that would cause settings like `apm-server.secret_key` to be named `APM_SERVER_APM_SERVER_SECRET_KEY`. To get rid of that, we'd need to (white-)list the settings under `apm-server`, and then we both need to main the whitelist AND it would be harder to explain to users because of the inconsistency in getting to `name` versus getting to `apm-server.secret_token`.

**Comment by roncohen** [comment]
Here's another datapoint. With the kubernetes setup for filebeat, we have a custom config: https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat-kubernetes.yaml#L12-L32

**Comment by graphaelli** [comment]
@roncohen Is this still relevant?  Docker image building is handled within the https://github.com/elastic/apm-server repo so let's either transfer it there or close this out.

**Pull request closed without merging**
