### PR TITLE
Add make image-dev

### PR DESCRIPTION
**Pull request by jahtalab**
We need a way to be able to build apm-server from master and make a docker image (to use in k8s infrastructure)
This is an attempt to achieve that. However this might not be the best way to do it so please make comments about how we can best achieve this.

cc @jarpy

### CODE REVIEW

**Comment by jarpy** [comment]
Hi,

If I understand your need correctly, this capability is already provided by `make build-from-local-artifacts`.

That approach decouples the product and image builds, feeding the tarball artefact from the former to the latter. There's also the advantage that this is the way we do it at release-time, so having that workflow well tested is a bonus!

**Comment by jahtalab** [comment]
Thanks @jarpy ,

'build-from-local-artifacts' script still tries to get `https://artifacts.elastic.co/downloads/apm-server/apm-server-7.0.0-alpha1-linux-x86_64.tar.gz` which does not exist so it fails. I'm not sure why it still needs to download the artifacts while I'm trying to build from local repo.

Also as a side note, `timeout` command doesn't exist on osx by default!

**Comment by jarpy** [comment]
Ah, sorry. It expects to have `$ARTIFACTS_DIR` set:

https://github.com/elastic/apm-server-docker/blob/master/Makefile#L55

The release manager always sets this. It's not obvious how to invoke it manually. My fault.

OSX? Docker is a collection of Linux technologies. We're not really targetting OSX as the primary build platform. :D

**Comment by jarpy** [comment]
Ah! I see now that `DOWNLOAD_URL_ROOT` must also be set.

https://github.com/elastic/apm-server-docker/blob/master/Makefile#L71

Let me write up an example when I have little bit more time.

**Comment by jahtalab** [comment]
I'm getting `timeout: command not found` on this line: https://github.com/elastic/apm-server-docker/blob/master/Makefile#L57, isn't that running `timeout` command on my local machine?

**Comment by Crazybus** [comment]
@jahtalab Correct. The `timeout` command is running on your local machine. However by default this command isn't installed on OSX. If you are a homebrew user you can easily add it with `brew install coreutils`.

You can then either add it to your path by adding `PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"` into your shell config. 

Or by adding an alias just for the timeout command `alias timeout=gtimeout`

**Comment by jarpy** [comment]
@jahtalab, yes, absolutely.

My point is that this repository is just not designed and tested for OSX. If you want to try, that's great, but please don't be shocked if things aren't quite right.

**Comment by graphaelli** [comment]
@jahtalab good to close this one out?

**Comment by jahtalab** [comment]
Thanks for the reminder @graphaelli !

**Pull request closed without merging**
